### ISSUE TITLE
Not able to build Hydra using mvn package 

### ISSUE THREAD

**Issue by srao712** [addthis/hydra#192]
While trying to build hydra package I got following error:

Failed to execute goal on project hydra-essentials: Could not resolve dependencies for project com.addthis.hydra:hydra-essentials:jar:5.5.13: Could not find artifact com.addthis:basis:jar:3.0.4 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

Please help in resolving. Tried older version 3.4 also. Same error with -P bdbje option.

**Comment by mspiegel** [comment]
Sorry we forgot to push the latest version of a few packages to maven central. The basis, bundle, and meshy libraries have been pushed it should take just a little while for those versions to propagate. We working on releasing the hydra-contrib modules our current build system is breaking on public releases of multimodule projects. In the interim you should be able to comment out those dependencies they are optional. Hopefully we will have a fix by the end of today.

**Comment by srao712** [comment]
I get a different error now. I have attached the error message
[Hydra Build Error.txt](https://github.com/addthis/hydra/files/37588/Hydra.Build.Error.txt)

**Comment by mspiegel** [comment]
Make sure that you have Java 8 installed and that maven is using Java 8.

**Comment by abramsm** [comment]
also, once you have Java 8 make sure to use `-P bdbje` in your mvn package command to include the bdb libraries.  for example

`mvn package -Pbdbje`

**Comment by tea-dragon** [comment]
I don't think we should have any hydra-contrib dependencies here anyway, and I'm relieved to see it only being referenced in dependency management. I can see how that might be theoretically useful to some projects seeking to use pom inheritance, but it's probably worth removing / commenting out for the sake of sanitation, yeah?

It looks like I was the one behind letting it linger, and I hereby fully repent my evil ways.

**Comment by srao712** [comment]
With Java 8 I made some progress. Got stuck again with following error. Got error in Hydar Data Module.

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Hydra Data Module 5.5.19-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/com/addthis/muxy/2.1.4/muxy-2.1.4.pom
[WARNING] The POM for com.addthis:muxy:jar:2.1.4 is missing, no dependency information available
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-math3/3.3/commons-math3-3.3.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-math3/3.3/commons-math3-3.3.pom (24 KB at 19.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/addthis/muxy/2.1.4/muxy-2.1.4.jar
Downloading: http://repo.maven.apache.org/maven2/org/apache/commons/commons-math3/3.3/commons-math3-3.3.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-math3/3.3/commons-math3-3.3.jar (1907 KB at 88.8 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hydra ............................................. SUCCESS [10.717s]
[INFO] Hydra Essentials Module ........................... SUCCESS [43.100s]
[INFO] Hydra KV Store Module ............................. SUCCESS [2:05.105s]
[INFO] Hydra Filters Module .............................. SUCCESS [5:50.065s]
[INFO] Hydra Data Module ................................. FAILURE [23.979s]
[INFO] Hydra Main API .................................... SKIPPED
[INFO] Hydra MQ Module ................................... SKIPPED
[INFO] Hydra Task Module ................................. SKIPPED
[INFO] Hydra Avro Module ................................. SKIPPED
[INFO] Hydra Main Module ................................. SKIPPED
[INFO] Hydra Uber Module ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9:14.225s
[INFO] Finished at: Mon Nov 23 13:03:54 IST 2015
[INFO] Final Memory: 26M/73M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hydra-data: Could not resolve dependencies for project com.addthis.hydra:hydra-data:jar:5.5.19-SNAPSHOT: Could not find artifact com.addthis:muxy:jar:2.1.4 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hydra-data

**Comment by tea-dragon** [comment]
It looks like that dependency (or parts of it) was missing from maven central, but I see it was re-uploaded about 5 hours ago. You might have better luck now.

**Comment by srao712** [comment]
Success! Thanks you all for the great and quick support!

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] hydra ............................................. SUCCESS [6.928s]
[INFO] Hydra Essentials Module ........................... SUCCESS [6.831s]
[INFO] Hydra KV Store Module ............................. SUCCESS [47.762s]
[INFO] Hydra Filters Module .............................. SUCCESS [19.475s]
[INFO] Hydra Data Module ................................. SUCCESS [2:39.631s]
[INFO] Hydra Main API .................................... SUCCESS [2.128s]
[INFO] Hydra MQ Module ................................... SUCCESS [24.384s]
[INFO] Hydra Task Module ................................. SUCCESS [1:07.338s]
[INFO] Hydra Avro Module ................................. SUCCESS [2:21.276s]
[INFO] Hydra Main Module ................................. SUCCESS [2:13.004s]
[INFO] Hydra Uber Module ................................. SUCCESS [1:56.355s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:06.028s
[INFO] Finished at: Tue Nov 24 09:55:10 IST 2015
[INFO] Final Memory: 39M/151M
[INFO] ------------------------------------------------------------------------
