### ISSUE TITLE
Not able to run samples as per user guide

### ISSUE THREAD

**Issue by srao712** [addthis/hydra#194]
Hi, I am trying to get started with Hydra, I am running Hydra in local configuration for testing. Where can I get sample job configurations and sample data? Where should the data be placed if I have a csv file? I managed to configure a job, however not able to provide input data. Please help. Your sample job with automatic data inject runs correctly.

**Comment by abramsm** [comment]
Hello -

LocalStack sets up a mesh server to stream data from the machine where
local stack is running.  When you created your local stack instance you
should get a directory:

hydra/hydra-local/streams

This is the default directory where hydra sources look for data.  I've
attached two files to this email.  job.conf is a sample job config that
reads data from a directory called 'data' which lives in the 'streams' sub
directory of your local stack.  The second file is called http.log.gz which
has some dummy apache log lines.  If you create a directory called 'data'
in the 'streams' directory and then copy the http.log.gz file into that
directory you should be able to run the attached job.conf file via spawn to
generate a simple tree.

Let me know how it goes.  We should probably add this (or similar) example
to the default localstack.

Thanks,
Matt

**Comment by srao712** [comment]
Hi Matt,

Thanks for the quick response. You missed to attach the files. Please resend.

 

Regards

Suresh Rao

**Comment by abramsm** [comment]
I see the attachments in the original email, can you double check?  Maybe
github is removing the attachments.  Send me your direct email.

**Comment by srao712** [comment]
Hi Matt,

I rechecked, the attachment is missing. Can you please forward it to my email address suresh.rao@live.in <mailto:suresh.rao@live.in> 

 

 

Thanks and Regards

 

Suresh Rao

**Comment by abramsm** [comment]
Here it is.  I've included plain text of job as well in the email.

""
source.mesh2:{
    mesh:{
        dateFormat:constant
        files:"/data/*"
    }
    processAllData:true
    format:{
        type:"column",

columns:["IP","IDENTD","USERID","TIMESTAMP","REQUEST","CODE","XFER"],
        tokens:{
            separator:" ",
            group:["\"", "[]"],
            pack:false,
        },
        lineFilter:{
            op:"exclude",
            match:["#.*"],
        },
    },
}

map.fields:["IP","TIMESTAMP","REQUEST","CODE", "XFER"]

map.filterOut:[
    {from:"TIMESTAMP", filter:[{split:" "}, {index:0}]}
    {op:"time", src:{field:"TIMESTAMP", format:"dd/MMM/yyyy:HH:mm:ss"},
dst:{field:"TIME", format:"native"}},
    {op:"time", src:{field:"TIME", format:"native"}, dst:{field:"DATE",
format:"yyMMdd-HHmmss", timeZone:"EST"}},
    {op:"field", from:"DATE", to:"DATE_YMD", filter:{op:"slice",to:6}},
    {debug {every:5}}
]


output.tree:{
    timeField:{field:"TIME", format:"native"}
    root:[
        {const:"root"}
        {field:"DATE_YMD"}
        {field:"CODE"}
        {field:"IP"}
    ]
}
""

**Comment by srao712** [comment]
Thanks Matt. But I have not got the sample data still.

 

Regards

Suresh Rao

**Comment by abramsm** [comment]
I think your email is blocking things (or github).  Here is a text snippet
from the sample data:

"""
64.242.88.10 - - [07/Mar/2004:16:05:49 -0800] "GET
/twiki/bin/edit/Main/Double_bounce_sender?topicparent=Main.ConfigurationVariables
HTTP/1.1" 401 12846
64.242.88.10 - - [07/Mar/2004:16:06:51 -0800] "GET
/twiki/bin/rdiff/TWiki/NewUserTemplate?rev1=1.3&rev2=1.2 HTTP/1.1" 200 4523
64.242.88.10 - - [07/Mar/2004:16:10:02 -0800] "GET
/mailman/listinfo/hsdivision HTTP/1.1" 200 6291
64.242.88.10 - - [07/Mar/2004:16:11:58 -0800] "GET
/twiki/bin/view/TWiki/WikiSyntax HTTP/1.1" 200 7352
64.242.88.10 - - [07/Mar/2004:16:20:55 -0800] "GET
/twiki/bin/view/Main/DCCAndPostFix HTTP/1.1" 200 5253
64.242.88.10 - - [07/Mar/2004:16:23:12 -0800] "GET
/twiki/bin/oops/TWiki/AppendixFileSystem?template=oopsmore¶m1=1.12¶m2=1.12
HTTP/1.1" 200 11382
64.242.88.10 - - [07/Mar/2004:16:24:16 -0800] "GET
/twiki/bin/view/Main/PeterThoeny HTTP/1.1" 200 4924
64.242.88.10 - - [07/Mar/2004:16:29:16 -0800] "GET
/twiki/bin/edit/Main/Header_checks?topicparent=Main.ConfigurationVariables
HTTP/1.1" 401 12851
64.242.88.10 - - [07/Mar/2004:16:30:29 -0800] "GET
/twiki/bin/attach/Main/OfficeLocations HTTP/1.1" 401 12851
64.242.88.10 - - [07/Mar/2004:16:31:48 -0800] "GET
/twiki/bin/view/TWiki/WebTopicEditTemplate HTTP/1.1" 200 3732
64.242.88.10 - - [07/Mar/2004:16:32:50 -0800] "GET
/twiki/bin/view/Main/WebChanges HTTP/1.1" 200 40520
64.242.88.10 - - [07/Mar/2004:16:33:53 -0800] "GET
/twiki/bin/edit/Main/Smtpd_etrn_restrictions?topicparent=Main.ConfigurationVariables
HTTP/1.1" 401 12851
64.242.88.10 - - [07/Mar/2004:16:35:19 -0800] "GET
/mailman/listinfo/business HTTP/1.1" 200 6379
64.242.88.10 - - [07/Mar/2004:16:36:22 -0800] "GET
/twiki/bin/rdiff/Main/WebIndex?rev1=1.2&rev2=1.1 HTTP/1.1" 200 46373
64.242.88.10 - - [07/Mar/2004:16:37:27 -0800] "GET
/twiki/bin/view/TWiki/DontNotify HTTP/1.1" 200 4140
64.242.88.10 - - [07/Mar/2004:16:39:24 -0800] "GET
/twiki/bin/view/Main/TokyoOffice HTTP/1.1" 200 3853
64.242.88.10 - - [07/Mar/2004:16:43:54 -0800] "GET
/twiki/bin/view/Main/MikeMannix HTTP/1.1" 200 3686
64.242.88.10 - - [07/Mar/2004:16:45:56 -0800] "GET
/twiki/bin/attach/Main/PostfixCommands HTTP/1.1" 401 12846
64.242.88.10 - - [07/Mar/2004:16:47:12 -0800] "GET /robots.txt HTTP/1.1"
200 68
64.242.88.10 - - [07/Mar/2004:16:47:46 -0800] "GET
/twiki/bin/rdiff/Know/ReadmeFirst?rev1=1.5&rev2=1.4 HTTP/1.1" 200 5724
64.242.88.10 - - [07/Mar/2004:16:49:04 -0800] "GET
/twiki/bin/view/Main/TWikiGroups?rev=1.2 HTTP/1.1" 200 5162
64.242.88.10 - - [07/Mar/2004:16:50:54 -0800] "GET
/twiki/bin/rdiff/Main/ConfigurationVariables HTTP/1.1" 200 59679
64.242.88.10 - - [07/Mar/2004:16:52:35 -0800] "GET
/twiki/bin/edit/Main/Flush_service_name?topicparent=Main.ConfigurationVariables
HTTP/1.1" 401 12851
64.242.88.10 - - [07/Mar/2004:16:53:46 -0800] "GET
/twiki/bin/rdiff/TWiki/TWikiRegistration HTTP/1.1" 200 34395
64.242.88.10 - - [07/Mar/2004:16:54:55 -0800] "GET
/twiki/bin/rdiff/Main/NicholasLee HTTP/1.1" 200 7235
64.242.88.10 - - [07/Mar/2004:16:56:39 -0800] "GET
/twiki/bin/view/Sandbox/WebHome?rev=1.6 HTTP/1.1" 200 8545
64.242.88.10 - - [07/Mar/2004:16:58:54 -0800] "GET
/mailman/listinfo/administration HTTP/1.1" 200 6459
"""

**Comment by srao712** [comment]
Thanks a lot. I am  able to run the job now.
