### ISSUE TITLE
custom user-agent？

### ISSUE THREAD

**Issue by wyl091256** [addthis/hydra#228]
hydra's user-agent is Mozilla/4.0 (Hydra),usually blocked by waf.
can we custom the user-agent?

**Comment by chppppp** [comment]
seriously, not being able to change the user-agent is painful

**Comment by tedpearson** [comment]
Which part of hydra are you using that is making calls with that user agent? I did a quick grep through the codebase for "Mozilla/" and didn't see it specified anywhere, so I'd need more information to trace your issue.

Also we are open to pull requests!

**Comment by chppppp** [comment]
On Hydra 8.6, if you run it through a proxy here are the headers it spits out:

`POST /index.php HTTP/1.0`
`Host: 1.2.3.4`
`User-Agent: Mozilla/5.0 (Hydra Proxy)`
`Content-Length: 116`
`Content-Type: application/x-www-form-urlencoded`
`Cookie: PHPSESSID=c8jfbkk5ka99sp1tnu41k83sgo`
`Connection: close`

quick google search suggests appending this to the attack string

`H=User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0`

but it just hangs. 

Am I in the wrong Hydra project or something? I noticed on the release page the highest is 5.6.73? Perhaps the hydra in this git is completely different from the one that is pulled via apt-get ?

Thanks for your reply tedpearson.

**Comment by chppppp** [comment]
I am in the wrong project. I am an idiot. 

Please ignore me. These are not the droids you're looking for.

**Comment by tedpearson** [comment]
lololol. Good luck with your issue!
